---

appVersion: "0.8.5"

images:
  type: LoadBalancer
  server:
    tag: 0.8.9

  agent:
    tag: 0.8.9

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - ci.dartagnan.devops.fuse.tikal.io

  # tls:
  #   - secretName: drone-tls
  #     hosts:
  #       - drone.domain.io

server:
  host: "http://ci.dartagnan.devops.fuse.tikal.io"

  env:
    DRONE_DEBUG: "false"
    DRONE_DATABASE_DRIVER: "sqlite3"
    DRONE_DATABASE_DATASOURCE: "/var/lib/drone/drone.sqlite"

    DRONE_PROVIDER: "github"
    DRONE_OPEN: "false"
    DRONE_GITHUB: "true"
    DRONE_ORGS: "tikalk"
    DRONE_ADMIN: "rafi,agayaga,liyak,ivantikal"
    # DRONE_GITHUB_CLIENT: "********************"

  envSecrets:
    drone-server-secrets:
      - DRONE_GITHUB_SECRET
      - DOCKER_USERNAME
      - DOCKER_PASSWORD

agent:
  env:
    DRONE_DEBUG: "false"
    DRONE_PLUGIN_PULL: "true"

dind:
  enabled: true
  driver: overlay2
