controller:

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  service:
    type: LoadBalancer

  stats:
    enabled: true

  metrics:
    enabled: true
